### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by PentiukPavel** [Road-Repair/backend#1]
1. Создать проект (Pyhon 3.12, DjangoRestFramework)

- Сразу настраиваем запуск в Docker?
- Как будем организовывать версионность API?

- [x] создать постоянную ветку development;
- [x] создать структуру проекта как в агропарке;
- [x] установить линтер black;
- [x] создать requirements.txt;
- [x] настроить pre-commit (линтер, несозданные миграции, пустая строка в конце);
- [x] настроить загрузку переменных среды в settings.py;
- [x] создать docker file;
- [x] #2
- [x] создать docker-compose для запуска проекта в Docker;
- [x] заполнить readme с инструкцией для фронтенда по запуску проекта.

**Comment by sblvkr** [comment]
Фронты высказывали желание самостоятельного, локального запуска бэкенда. Поэтому нужен докер и простенькую инструкцию для них

**Comment by robky** [comment]
Ок. Сделаю
